services:

  swagger-ui:
    image: swaggerapi/swagger-ui
    depends_on:
      traefik:
        condition: service_started
    networks:
      traefik: { }
      default: { }
    deploy: &labels
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.constraint-label=traefik
        - traefik.http.routers.${COMPOSE_PROJECT_NAME?}-swagger.rule=Host(`${SWAGGER_HOST?}`)
        - traefik.http.services.${COMPOSE_PROJECT_NAME?}-swagger.loadbalancer.server.port=8080
    <<: *labels